// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bepkmkudnoyoxjjmeiju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlcGtta3Vkbm95b3hqam1laWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjgwMDMsImV4cCI6MjA2NTI0NDAwM30.LCqIaC094-OJARfLae2vxRGpqtlqqpNH2gcztqExmNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);